# Built with Jekyll 3.2.0

# Setup
title:               reniew's blog
tagline:             'cs and deep learning'
description:         "reniew's blog"
url:                 'http://reniew.github.io'
baseurl:
encoding: utf-8

# About/contact
author:
  name:              Junghyun Cho
  url:               https://github.com/reniew
  email:             reniew1@nate.com

disqus_url: 'https://reniew.disqus.com/'
disqus_id: 'reniew'

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Contents:
    - '/contents/'
  About:
    - '/about/'

# About/contact
author:
  name: reniew
  description: <strong>JungHyun</strong>
  gravatar: 0a638fc7996869b1b67fb90ccf77dcfe # md5 hash of your email address
  contact:
    #linkedin:  <hide>
    github:    https://github.com/reniew
    facebook:  https://www.facebook.com/people/%EC%A1%B0%EC%A4%91%ED%98%84/100001883067095
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:reniew1@nate.com

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
